# @name get-all-polls 
GET http://localhost:3333/polls

###

# @name get-poll //Frameworks NodeJs id
GET http://localhost:3333/polls/aa86767c-1902-4ba0-b3fb-0fe3e6f5d989

###

# @name create-poll

POST http://localhost:3333/polls
Content-Type: application/json

{
  "title": "Frameworks Frontend",
  "options": ["ReactJS", "Vue", "Svelte"]
}

###

# @name vote-on-poll //Frameworks NodeJs id

POST http://localhost:3333/polls/b2d02afd-886f-4df3-9f12-e199f38a8c4a/votes
Content-Type: application/json

{
  "pollOptionId": "a83f6acf-27c7-4ba1-aa1b-a8ef12d2e4ae"
}

